channel: stable
addons:
  appdaemon-with-face-recognition:
    repository: engrbm87/appdaemon-with-face-recognition
    target: appdaemon-with-face-recognition
    image: engrbm87/appdaemon-with-face-recognition-{arch}